language: node_js
node_js:
- '8'
script:
- npm test
- npm run build
env:
  global:
  - REACT_APP_GRAPHQL_HOST=https://api.thatconference.com
  - REACT_APP_GRAPHQL_WSS_HOST=wss://api.thatconference.com
deploy:
  project: bigredbutton-3fe9b
  provider: firebase
  skip_cleanup: true
  message: 'Build # $TRAVIS_BUILD_NUMBER'
  token:
    secure: IpUsHlCpRrSfDRGMAqn312oP/aF/PdY4Qdx33uYrCya7idqmVXTLeQwc3xSzkZyIdvCatBvBpIhXkqT5Dzx5xL/u/midUV4XfWUf3DEUWBb0C+V8nAbysbF2gWLe1mAllV3rq3vJVQllamFSPPqJuueHvZ9eQKtj13eIbMgV3SZaj0aD4FY5JOEky+rmfzVIBfEJNMDwoal86MLWcXd8ydgLPQcX0GEFWxGZEA0NavWmeqQgHIGg8gh4Xw+EnOOvH/lES598YSS/G68nNkeLfqNT8HuJYQSkZpOjJDFW+xI9lxVqj6dF22GciQu4CKJeqtLguYnsYw28yEK2tWIijONa8m7bWtwda7SEEX3TGfMfMAMlLSAYlMq+3LiA8qIgOcbIxMhtPHb+vfsmsRXXoCOnFb2fQHPwJrAlbubKe7VZ4KYmWFwMeNiH+0z//9LtBy7oP3y/G5JXoeflNkZzAqQpLFUJ3sowM9apGcUoN5KUlDVVocUebyzZQXB0lp05lCaX9qZyEaOPbR2N/eJb1a97th230FJcKJG3ca5qoiey5JQFNXjyiwWpdnipbMdX5aAGfUTl/GZLan11nGmkCk8pTr+EUhqKIG2ujElCj83xZhqHGhU1JXfRm5ZpfwkLgyJAwM/8Yj+yDbP+k8VNvDeyas8BlCbD1i/DcacB8BQ=
