language: node_js
node_js:
- '8'
script:
- npm test
- npm run build
env:
  global:
  - REACT_APP_GRAPHQL_HOST=https://api.thatconference.com
  - REACT_APP_GRAPHQL_WSS_HOST=wss://api.thatconference.com
deploy:
  project: BigRedButton
  provider: firebase
  token:
    secure: gRKARx1AKEuD8e9u6zlMHiqCBtZLcchoYiiTsnWiCDATdL/LNTnXV6zrqj9+mQgVjKsgWvgFCBqT1+nytftSCUkOmx3fHpcl/YNXrBsh6TMMfRyi2WxS9BAbnQEhWg1HjGUrysNu6pdcqp0Ejno2EPgzHP8Wm8GZFhFJZDs9so6Gl/g2dszkygeb0T8dFjue9aquAyTNK/2mVO/L84YEyUxQOvJilsnWTUo/bGU5aqqnoeVTnWjjH4d4g19y1dhOq0l3sOm5JA6D/82rAbbc//G6clmQIPIdNUzZ4FQ74DikQhbDQ4vr5i3uKI4jW9erlUrL0DWzN0mjzbmh8xNMzoRn1qqYwCDX1GYog/b9A0vjrSHnzpCHCmJMiu+vNvL7lAi1plzzLWx84HOeN2aoQatULBrkzdcFAFhK/dvEW2FCMIXQbJJDV5G4l/IaXiA7sO2oThi3gt/62s8v2AJeSsBjdD1cPwQxcOcUNYg/nZZ6kOPUjk/Myy6VCtu74KQ+HT+QteNleX+iTBMXZNS/eBmmkuEoDNensoeouGIecLtWnip3hQ+AeiWKDR17BR7zH0eTt32yZRVP71JwWn+mHVXAD0O6xEk7+K6AZp3tbnCAXx4AmeoxdL3CZvcVaX6rynqwaAXTZ6K3zPvBHdLammlTPLBLV7oSwERIzLpp42Q=
  skip_cleanup: true
  message: 'Build # $TRAVIS_BUILD_NUMBER'
