language: node_js
node_js:
- '8'
script:
- npm test
- npm run build
env:
  global:
  - REACT_APP_GRAPHQL_HOST=https://api.thatconference.com
  - REACT_APP_GRAPHQL_WSS_HOST=wss://api.thatconference.com
deploy:
  project: BigRedButton
  provider: firebase
  skip_cleanup: true
  message: 'Build # $TRAVIS_BUILD_NUMBER'
  token:
    secure: YKESJGtpB3IxllABydfomVda8X0cW3tevIKEM3H9vw63FXj2+ignFar+Fk2ed50XhwxWwC3j/iwizJlO8s8OYWU5tueitTSJ5GakcJvy4vzVK0GoJgElrd3WYaJiINXvv1t5EwxWJnlPzxd6I2+2pcPiGy2S71MR/4fMtGM5h5RpeGiBajj3jmZVpy2A5WoaQ9StzlnzfNJ8F00I3YjlLMUwO4y3FRqVMJCmQSQa35w5ALSFGKuHO/xqoHCE/5lQAzBJV9OE42uT2PWhKEBpNQRuHHGERmj2PBROQ42ohncw5nku/7/prcOo5auEkizQya/Nq4HNClwyKHuWVyd2SKAPTNyfMTTSrMYgx5TK+S+cn9Ge0W3d12jw3axEnzEH4v94xZ7OZR+PZi2pHTYCcPM1DFjKuoqAU0/hHROgr4FQ+329iao4WPokT/l5au8yqsLcf0HqhWNvxEqBi5PHFc2Gd9aKfxjcIYmW4bhUTFdOXO5MBe9jAtW9Sjlv36k0Kat4qqCLFaIG8Jp8xwCRdh8GiTr9bAAzZnyyf3BRJ2VaW5lj/gXasDRI80GA8sCFsx6dm3Mox4eALi7bBYNKwUcnwqwfp5o0f/v6DcAaEdv89S4bFbE0jX5ZUymiJ1mFlCT/OJ6uEwISC07DXC7tvJzekCKLF9eABPM/uZEePoA=
