language: node_js
node_js:
- '10.15.0'
script:
- npm test
- npm run build
env:
  global:
  - REACT_APP_GRAPHQL_HOST=https://api.thatconference.com
  - REACT_APP_GRAPHQL_WSS_HOST=wss://api.thatconference.com
deploy:
  project: bigredbutton-3fe9b
  provider: firebase
  skip_cleanup: true
  message: 'Build # $TRAVIS_BUILD_NUMBER'
  token:
    secure: tpsP81MRc1piIUG8JrYKC3GPw6/hp48AH9VbBJm72TykmuEdZS8z6NtUv4TVLm0njQOlnNkLcmd/QFlrm/ib5VYJgVWQ/sHqR2+3Gmk5Q2qZcJnprfDGTuTakB1exdXfwOtlO+a9BRN9F5E+UATUAfxpbOXmq7mJF/2k5JO2rEBaQfxAEgC5hytDMbsM1e01HBSQV/OySkcmxmdC6tHhTXB30cV0RJ5N87nWodnMT1Rs0+8kVn5+6pD4vT9oD3yE+x4BkBekMhL9jnmKGccqDRoPwlD/p0Y9+4bf9K7QrGGL0D0I9G4TFkd9sz/XQCyDuKWtfPEoXsR9ruRT5AbGiqxMtkInAZvvD5W8qaDT35MsKpdXnVyLhWw2yKa6+rnBN5gE8bYqkGsybonszCNV7dyrx01euh1x3wh/51BGlTWMs/N2sbXhJvphlrgxTvJ63cr8zYU4bk02V2EkA1oqYMLuazn3EXfuuFNncLSVjSfoqWTFVFTvDObhZIV+C5dc1rMI/KRUETYCt6RcYajGldUqhyjZl5yycwQ4+dLn1EeevMYPAyjAwoECRSogtrU0Jdn6D7/BZywkcIsFuzrjbfb/yxijDcLJ6uPSpP3SzNcXipWayHOb2kzffjEq6N8zLDMQcYsxhU++0WmlFOAhFg4oz6UWl0OCXQCvrMKC8dQ=
